config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'comments/create'
  get 'comments/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root 'tweets#index'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get 'follows'
      get 'followers'
    end
  end
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments

  validates :content, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image
  validates :name, presence: true
  
  has_many :tweets, dependent: :destroy
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments
  has_many :comments_tweets, through: :comments, source: :tweet


  has_many :relationships, foreign_key: :follow_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :follow

  def followed_by?(user)
    reverse_of_relationships.find_by(follow_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    comment.tweet_id = params[:tweet_id]
    comment.save
    redirect_to tweet_path(comment.tweet)
  end

  def destroy
    comment = Comment.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    comment.destroy
    redirect_to tweet_path(comment.tweet)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweets_path
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to user_path(params[:user_id])
  end

  def destroy
    follow = current_user.relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to user_path(params[:user_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: "DESC")
  end

  def create
    @tweet = Tweet.new(tweets_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      @tweets = Tweet.all
      render :index
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  private

  def tweets_params
    params.require(:tweet).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
    @favorite_tweets = @user.favorite_tweets
    @comments_tweets = @user.comments_tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Successfully edited.'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    @users = User.find(params[:id]).followings
  end

  def followers
    @users = User.find(params[:id]).followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workdir</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Twitter Clone</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><%= link_to "マイページ", user_path(current_user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/tweets/index.html.erb
<%= form_with(model: @tweet, class: "tweet_form", local: true) do |f| %>
  <%= render 'layouts/error_messages', model: @tweet %>
  <%= f.text_area :content, class: "materialize-textarea" %>
  <%= f.submit 'ツイートする', class: "waves-effect waves-light btn" %>
<% end %>

<div class="tweet-box">
  <% @tweets.each do |tweet| %>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <%= link_to user_path(tweet.user) do %>
            <%= attachment_image_tag tweet.user, :user_image, :fill, 75, 75,fallback: "no_image.jpg", size:'75x75', format: 'jpeg',class: "circle image" %>
          <% end %>
          <p class="tweet"><%= link_to tweet.content, tweet_path(tweet) %></p>
        </div>
        <div class="card-action">
          <% if user_signed_in? %>
            <% if tweet.favorited_by?(current_user) %>
              <%= link_to tweet_favorites_path(tweet.id), method: :delete do %>
                <i class="material-icons favorite">favorite</i><span class="favorite"><%= tweet.favorites.count %></span>
              <% end %>
            <% else %>
              <%= link_to tweet_favorites_path(tweet.id), method: :post do %>
                <i class="material-icons favorite_border">favorite_border</i><span class="favorite_border"><%= tweet.favorites.count %></span>
              <% end %>
            <% end %>
          <% end %>
          <%= link_to tweet_path(tweet) do %>
            <i class="material-icons comment">comment</i><span class="comment"><%= tweet.comments.count %></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="tweet-show-box">
  <%= link_to user_path(@tweet.user) do %>
    <%= attachment_image_tag @tweet.user, :user_image, :fill, 75, 75,fallback: "no_image.jpg", size:'75x75', format: 'jpeg',class: "circle image" %>
  <% end %>
  <span class="tweet"><%= link_to @tweet.content, tweet_path(@tweet) %></span>
  <% if @tweet.user_id == current_user.id %>
    <span class="delete-btn">
      <%= link_to tweet_path(@tweet), method: :delete, data: {confirm: "このツイートを削除しますか？"} do %>
        <i class="material-icons">delete</i>
      <% end %>
    </span>
  <% end %>
</div>

<%= form_with(model: [@tweet, @comment], local: true, class: "form") do |f| %>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :content %>
  </div>
  <%= f.submit 'コメントする', class: "save-btn btn" %>
<% end %>

<table class="comment_box">
  <% @tweet.comments.each do |comment| %>
    <tbody>
      <tr>
        <td class="user-image-td">
          <%= link_to user_path(comment.user_id) do %>
            <%= attachment_image_tag comment.user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle image" %>
          <% end %>
        </td>
        <td><span class="tweet"><%= comment.content %></span></td>
        <% if comment.user_id == current_user.id %>
          <td class="delete-btn-td">
            <%= link_to tweet_comments_path(comment.tweet), method: :delete, data: {confirm: "このツイートを削除しますか？"}  do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
        <% end %>
      <tr>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, class: "form") do |f| %>
  <%= render 'layouts/error_messages', model: @user %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :icon %><br>
    <span class="btn btn-file">
      画像を選択<%= f.attachment_field :user_image %>
    </span>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "materialize-textarea" %>
  </div>

  <div class="actions">
    <%= f.submit '保存', class: "save-btn btn" %>
  </div>
<% end %>

app/views/users/followers.html.erb
<h2>フォロワー</h2>
<table class="follow-page">
    <% @users.each do |user| %>
        <tr>
        <%= link_to user_path(user) do %>
        <td><%= attachment_image_tag user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle" %></td>
        <% end %>
        <td><span class="username"><%= user.name %></span></td>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <td><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></td>
        <% else %>
            <tr><%=link_to "フォロー", user_relationships_path(user.id), method: :post %></td>
        <% end %>
    <% end %>
    </tr>
    <% end %>
</table>

app/views/users/follows.html.erb
<h2>フォロー</h2>
<table class="follow-page">
    <% @users.each do |user| %>
        <tr>
            <td>
                <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle" %>
                <% end %>
            </td>
            <td><span class="username"><%= user.name %></span></td>
    <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
                <td><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></td>
            <% else %>
                <tr><%=link_to "フォロー", user_relationships_path(user.id), method: :post %></td>
            <% end %>
    <% end %>
        </tr>
    <% end %>
</table>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="profile-box">
  <%= attachment_image_tag @user, :user_image, :fill, 105, 105,fallback: "no_image.jpg", size:'105x105', format: 'jpeg',class: "circle" %>
  <p class="username"><%= @user.name %></p>
  <p><%= @user.introduction %></p>
	
	<%=link_to "フォロー", follows_user_path(@user) %>
	<%=link_to "フォロワー", followers_user_path(@user) %>

	<% if current_user != @user %>
		<% if @user.followed_by?(current_user) %>
			<%= link_to 'フォロー中', user_relationships_path(@user), class: "profile-edit-btn btn", method: :delete %>
		<% else %>
			<%= link_to 'フォロー', user_relationships_path(@user), class: "profile-edit-btn btn", method: :post %>
		<% end %>
	<% end %>

	<% if current_user == @user %>
  	<%= link_to 'プロフィールを編集', edit_user_path(@user), class: "profile-edit-btn btn" %>
	<% end %>
</div>


<div class="user_posted">
		<ul class="tab clearfix">
		  <li class="active">ツイート</li>
		  <li>コメント</li>
		  <li>いいね</li>
		</ul>

		<div class="area">
		  <ul class="show">
				<table class="table">
          <% @tweets.each do |tweet| %>
					  <tbody>
					    <tr>
								<%= link_to(user_path(tweet.user)) do %>
									<td class="user-image-td"><%= attachment_image_tag @user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle" %></td>
								<% end %>
								<td><%= link_to tweet.content, tweet_path(tweet) %></td>
					    </tr>
					  </tbody>
				  <% end %>
				</table>
		  </ul>
		  <ul>
				<table class="table">
					<% @comments_tweets.each do |tweet| %>
					  <tbody>
					    <tr>
								<%= link_to(user_path(tweet.user)) do %>
									<td class="user-image-td"><%= attachment_image_tag @user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle" %></td>
								<% end %>
								<td><%= link_to tweet.content, tweet_path(tweet) %></td>
					    </tr>
					  </tbody>
				  <% end %>
				</table>
		  </ul>
		  <ul>
				<table class="table">
					<% @favorite_tweets.each do |tweet| %>
					  <tbody>
					    <tr>
								<%= link_to(user_path(tweet.user)) do %>
									<td class="user-image-td"><%= attachment_image_tag @user, :user_image, :fill, 50, 50,fallback: "no_image.jpg", size:'50x50', format: 'jpeg',class: "circle" %></td>
								<% end %>
								<td><%= link_to tweet.content, tweet_path(tweet) %></td>
					    </tr>
					  </tbody>
				  <% end %>
				</table>
		  </ul>
		</div>
	</div>